spring:
  datasource:
    # MySQL
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      show-sql: false
